/**
 * This file was auto-generated by openapi-typescript.
 * Do not make direct changes to the file.
 */

export interface paths {
  "/": {
    get: {
      responses: {
        /** OK */
        200: unknown;
      };
    };
  };
  "/profile": {
    get: {
      parameters: {
        query: {
          id?: parameters["rowFilter.profile.id"];
          email?: parameters["rowFilter.profile.email"];
          provider?: parameters["rowFilter.profile.provider"];
          full_name?: parameters["rowFilter.profile.full_name"];
          avatar_type?: parameters["rowFilter.profile.avatar_type"];
          pin?: parameters["rowFilter.profile.pin"];
          confirmed_at?: parameters["rowFilter.profile.confirmed_at"];
          created_at?: parameters["rowFilter.profile.created_at"];
          /** Filtering Columns */
          select?: parameters["select"];
          /** Ordering */
          order?: parameters["order"];
          /** Limiting and Pagination */
          offset?: parameters["offset"];
          /** Limiting and Pagination */
          limit?: parameters["limit"];
        };
        header: {
          /** Limiting and Pagination */
          Range?: parameters["range"];
          /** Limiting and Pagination */
          "Range-Unit"?: parameters["rangeUnit"];
          /** Preference */
          Prefer?: parameters["preferCount"];
        };
      };
      responses: {
        /** OK */
        200: {
          schema: definitions["profile"][];
        };
        /** Partial Content */
        206: unknown;
      };
    };
    post: {
      parameters: {
        body: {
          /** profile */
          profile?: definitions["profile"];
        };
        query: {
          /** Filtering Columns */
          select?: parameters["select"];
        };
        header: {
          /** Preference */
          Prefer?: parameters["preferReturn"];
        };
      };
      responses: {
        /** Created */
        201: unknown;
      };
    };
    delete: {
      parameters: {
        query: {
          id?: parameters["rowFilter.profile.id"];
          email?: parameters["rowFilter.profile.email"];
          provider?: parameters["rowFilter.profile.provider"];
          full_name?: parameters["rowFilter.profile.full_name"];
          avatar_type?: parameters["rowFilter.profile.avatar_type"];
          pin?: parameters["rowFilter.profile.pin"];
          confirmed_at?: parameters["rowFilter.profile.confirmed_at"];
          created_at?: parameters["rowFilter.profile.created_at"];
        };
        header: {
          /** Preference */
          Prefer?: parameters["preferReturn"];
        };
      };
      responses: {
        /** No Content */
        204: never;
      };
    };
    patch: {
      parameters: {
        query: {
          id?: parameters["rowFilter.profile.id"];
          email?: parameters["rowFilter.profile.email"];
          provider?: parameters["rowFilter.profile.provider"];
          full_name?: parameters["rowFilter.profile.full_name"];
          avatar_type?: parameters["rowFilter.profile.avatar_type"];
          pin?: parameters["rowFilter.profile.pin"];
          confirmed_at?: parameters["rowFilter.profile.confirmed_at"];
          created_at?: parameters["rowFilter.profile.created_at"];
        };
        body: {
          /** profile */
          profile?: definitions["profile"];
        };
        header: {
          /** Preference */
          Prefer?: parameters["preferReturn"];
        };
      };
      responses: {
        /** No Content */
        204: never;
      };
    };
  };
  "/timeline": {
    get: {
      parameters: {
        query: {
          task?: parameters["rowFilter.timeline.task"];
          id?: parameters["rowFilter.timeline.id"];
          event?: parameters["rowFilter.timeline.event"];
          description?: parameters["rowFilter.timeline.description"];
          timestamp?: parameters["rowFilter.timeline.timestamp"];
          /** Filtering Columns */
          select?: parameters["select"];
          /** Ordering */
          order?: parameters["order"];
          /** Limiting and Pagination */
          offset?: parameters["offset"];
          /** Limiting and Pagination */
          limit?: parameters["limit"];
        };
        header: {
          /** Limiting and Pagination */
          Range?: parameters["range"];
          /** Limiting and Pagination */
          "Range-Unit"?: parameters["rangeUnit"];
          /** Preference */
          Prefer?: parameters["preferCount"];
        };
      };
      responses: {
        /** OK */
        200: {
          schema: definitions["timeline"][];
        };
        /** Partial Content */
        206: unknown;
      };
    };
    post: {
      parameters: {
        body: {
          /** timeline */
          timeline?: definitions["timeline"];
        };
        query: {
          /** Filtering Columns */
          select?: parameters["select"];
        };
        header: {
          /** Preference */
          Prefer?: parameters["preferReturn"];
        };
      };
      responses: {
        /** Created */
        201: unknown;
      };
    };
    delete: {
      parameters: {
        query: {
          task?: parameters["rowFilter.timeline.task"];
          id?: parameters["rowFilter.timeline.id"];
          event?: parameters["rowFilter.timeline.event"];
          description?: parameters["rowFilter.timeline.description"];
          timestamp?: parameters["rowFilter.timeline.timestamp"];
        };
        header: {
          /** Preference */
          Prefer?: parameters["preferReturn"];
        };
      };
      responses: {
        /** No Content */
        204: never;
      };
    };
    patch: {
      parameters: {
        query: {
          task?: parameters["rowFilter.timeline.task"];
          id?: parameters["rowFilter.timeline.id"];
          event?: parameters["rowFilter.timeline.event"];
          description?: parameters["rowFilter.timeline.description"];
          timestamp?: parameters["rowFilter.timeline.timestamp"];
        };
        body: {
          /** timeline */
          timeline?: definitions["timeline"];
        };
        header: {
          /** Preference */
          Prefer?: parameters["preferReturn"];
        };
      };
      responses: {
        /** No Content */
        204: never;
      };
    };
  };
  "/rpc/add_avatar_change": {
    post: {
      parameters: {
        body: {
          args: { [key: string]: unknown };
        };
        header: {
          /** Preference */
          Prefer?: parameters["preferParams"];
        };
      };
      responses: {
        /** OK */
        200: unknown;
      };
    };
  };
  "/rpc/add_sign_in": {
    post: {
      parameters: {
        body: {
          args: { [key: string]: unknown };
        };
        header: {
          /** Preference */
          Prefer?: parameters["preferParams"];
        };
      };
      responses: {
        /** OK */
        200: unknown;
      };
    };
  };
  "/rpc/add_name_change": {
    post: {
      parameters: {
        body: {
          args: { [key: string]: unknown };
        };
        header: {
          /** Preference */
          Prefer?: parameters["preferParams"];
        };
      };
      responses: {
        /** OK */
        200: unknown;
      };
    };
  };
  "/rpc/create_new_profile": {
    post: {
      parameters: {
        body: {
          args: { [key: string]: unknown };
        };
        header: {
          /** Preference */
          Prefer?: parameters["preferParams"];
        };
      };
      responses: {
        /** OK */
        200: unknown;
      };
    };
  };
}

export interface definitions {
  profile: {
    /**
     * Note:
     * This is a Primary Key.<pk/>
     */
    id: string;
    email: string;
    provider: string;
    full_name?: string;
    avatar_type: string;
    pin?: string;
    confirmed_at: string;
    created_at: string;
  };
  timeline: {
    /**
     * Note:
     * This is a Primary Key.<pk/>
     */
    task: number;
    id: string;
    event: string;
    description?: string;
    timestamp: string;
  };
}

export interface parameters {
  /** Preference */
  preferParams: "params=single-object";
  /** Preference */
  preferReturn: "return=representation" | "return=minimal" | "return=none";
  /** Preference */
  preferCount: "count=none";
  /** Filtering Columns */
  select: string;
  /** On Conflict */
  on_conflict: string;
  /** Ordering */
  order: string;
  /** Limiting and Pagination */
  range: string;
  /** Limiting and Pagination */
  rangeUnit: string;
  /** Limiting and Pagination */
  offset: string;
  /** Limiting and Pagination */
  limit: string;
  /** profile */
  "body.profile": definitions["profile"];
  "rowFilter.profile.id": string;
  "rowFilter.profile.email": string;
  "rowFilter.profile.provider": string;
  "rowFilter.profile.full_name": string;
  "rowFilter.profile.avatar_type": string;
  "rowFilter.profile.pin": string;
  "rowFilter.profile.confirmed_at": string;
  "rowFilter.profile.created_at": string;
  /** timeline */
  "body.timeline": definitions["timeline"];
  "rowFilter.timeline.task": string;
  "rowFilter.timeline.id": string;
  "rowFilter.timeline.event": string;
  "rowFilter.timeline.description": string;
  "rowFilter.timeline.timestamp": string;
}

export interface operations {}

export interface external {}
